Fix incorrect file open mode in utils/change_dev_size
An error was thrown before the change -
TypeError: cannot use a string pattern on a bytes-like object
It occurred because the file is a text file and it has been opened in binary mode.